### ISSUE TITLE
Unable to converge on keypoint

### ISSUE THREAD

**Issue by chenzeyuczy** [Superlee506/Mask_RCNN#25]
Hey @Superlee506 . It's a nice job for you to modify the project for keypoint detection. I've use your codes for face landmark detections, which outputs less keypoints than the human pose. However, it is tough for me to makes the output converge. The keypoint loss gets stable at about 2.8 or so while the 4 other losses for ROI detection is lower than 0.3. The keypoint detection is not accurate during the test phase. I wonder whether you can reproduce the result from the original paper and that I'm curious about the curve for keypoint mask loss.

**Comment by Superlee506** [comment]
Thanks for your interest,  you can refer to Caffe2 for reproduction,  I also wonder about the results in MaskCNN, because the model often can't distinguish the symmetrical  keypoints. While in the [densepose ](https://github.com/facebookresearch/DensePose), they make use of cascade network to  achieve better performance, you can refer to the newest work.
